num=int(input('digite um numero:'))
i=str('=')
print('{:=^29}'.format(i))
print('tabuada de somas:')
print('{:=^29}'.format(i))
print('{}+{}={}'.format(num, 1, num+1))
print('{}+{}={}'.format(num, 2, num+2))
print('{}+{}={}'.format(num, 3, num+3))
print('{}+{}={}'.format(num, 4, num+4))
print('{}+{}={}'.format(num, 5, num+5))
print('{}+{}={}'.format(num, 6, num+6))
print('{}+{}={}'.format(num, 7, num+7))
print('{}+{}={}'.format(num, 8, num+8))
print('{}+{}={}'.format(num, 9, num+9))
print('{}+{}={}'.format(num, 10, num+10))
print('{:=^29}'.format(i))
print('tabuada de subtração')
print('{:=^29}'.format(i))
print('{}*{}={}'.format(num, 1, num-1))
print('{}*{}={}'.format(num, 2, num-2))
print('{}*{}={}'.format(num, 3, num-3))
print('{}*{}={}'.format(num, 4, num-4))
print('{}*{}={}'.format(num, 5, num-5))
print('{}*{}={}'.format(num, 6, num-6))
print('{}*{}={}'.format(num, 7, num-7))
print('{}*{}={}'.format(num, 8, num-8))
print('{}*{}={}'.format(num, 9, num-9))
print('{}*{}={}'.format(num, 10, num-10))
print('{:=^29}'.format(i))
print('tabuada de multiplicação:')
print('{:=^29}'.format(i))
print('{}*{}={}'.format(num, 1, num*1))
print('{}*{}={}'.format(num, 2, num*2))
print('{}*{}={}'.format(num, 3, num*3))
print('{}*{}={}'.format(num, 4, num*4))
print('{}*{}={}'.format(num, 5, num*5))
print('{}*{}={}'.format(num, 6, num*6))
print('{}*{}={}'.format(num, 7, num*7))
print('{}*{}={}'.format(num, 8, num*8))
print('{}*{}={}'.format(num, 9, num*9))
print('{}*{}={}'.format(num, 10, num*10))
print('{:=^29}'.format(i))
print('tabuada de divisão:')
print('{:=^29}'.format(i))
print('{}*{}={:.1f}'.format(num, 1, num/1))
print('{}*{}={:.1f}'.format(num, 2, num/2))
print('{}*{}={:.1f}'.format(num, 3, num/3))
print('{}*{}={:.1f}'.format(num, 4, num/4))
print('{}*{}={:.1f}'.format(num, 5, num/5))
print('{}*{}={:.1f}'.format(num, 6, num/6))
print('{}*{}={:.1f}'.format(num, 7, num/7))
print('{}*{}={:.1f}'.format(num, 8, num/8))
print('{}*{}={:.1f}'.format(num, 9, num/9))
print('{}*{}={:.1f}'.format(num, 10, num/10))
print('{:=^29}'.format(i))