n=input('digite algo:')
print('tipo primitivo', type(n))
print('é alfabetico?', n.isalpha())
print('é alfanumerico?', n.isalnum())
print('está em minusculo?', n.islower())
print('está em maiusculo?', n.isupper())
print('pussui titulo?', n.istitle())
print('é um valor numerico?', n.isnumeric())
print('é valido no paython?', n.isidentifier())
print('pussui espaços?', n.isspace())